[package]
name = "netlib"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/netlib"
homepage = "https://github.com/hilbert-space/netlib"
description = "Netlib."
